# Generated by Django 3.0.4 on 2020-03-22 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
        ('account', '0002_auto_20200322_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='post',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='post.Post'),
        ),
    ]
