version: '3.3'

services:
  db:
    image: postgis/postgis:12-3.0-alpine
    environment:
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: 'password'
  test:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      sh -c "sleep 5s && make test"
    volumes:
      - .:/social_road
    ports:
      - "80:8000"
    depends_on:
      - db
