.PHONY: test-requirements
test-requirements: requirements
	pip install --no-cache-dir -r requirements_test.txt

.PHONY: test-install
test-install: test-requirements
	apt-get update
	apt-get install -y gdal-bin python3-gdal proj-bin

.PHONY: test
test: migrate
	pytest -k-slow --cov=./ --cov-report=xml

.PHONY: test-slow
test-slow: migrate
	pytest --cov=./ --cov-report=xml
