# Generated by Django 3.0.4 on 2020-03-22 16:32

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VoiesMel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('troncon', models.CharField(max_length=5)),
                ('insee', models.CharField(max_length=4)),
                ('commune', models.CharField(max_length=255)),
                ('id_voie', models.CharField(max_length=7)),
                ('nom_rue', models.CharField(max_length=255)),
                ('code_traf', models.CharField(max_length=1, null=True)),
                ('trafic', models.CharField(max_length=255, null=True)),
                ('code_dome', models.CharField(max_length=1, null=True)),
                ('domanialit', models.CharField(max_length=255, null=True)),
                ('code_sens', models.CharField(max_length=1, null=True)),
                ('sens', models.CharField(max_length=255, null=True)),
                ('rivoli', models.CharField(max_length=4)),
                ('genre', models.CharField(max_length=255, null=True)),
                ('road', django.contrib.gis.db.models.fields.LineStringField(srid=4326)),
            ],
        ),
    ]
