# Generated by Django 3.0.4 on 2020-03-22 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_post_travel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='travel',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='post.Travel'),
        ),
    ]
