name: Python test

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 6
      matrix:
        python-version: [3.6]
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v2
    - name: Run test
      run: |
        make docker-test
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        flags: unittests
